@startuml
class FloorMovement {
    + gameManager : GameManager
    + baseSpeed : float = 5f
    + obstaclePrefab : GameObject
    + minYpositionObstacle : float
    + maxYpositionObstacle : float = 5
    + minYscaleObstacle : float = 2
    + maxYscaleObstacle : float = 6
    + maxXspeed : float = 20
    + speedIncreaseFactor : int = 60
    + scoreNumber : float = 0
    + scoreText : Text
    Start() : void
    Update() : void
}
MonoBehaviour <|-- FloorMovement
@enduml
